import os
from string import Template


class PowershellHelpHeader:
    def __init__(self, parameters, origin_file, links=None, description='Modify at own risk #autogenerated'):
        self.parameters = parameters
        self.origin_file = origin_file
        self.links = links
        self.description = description

    def get_item(self,  k, v):
        return "."+k.upper()+"\n\t"+v+"\n\n"

    def get_param_item(self,  k, v):
        paramTemplate = Template(
            '''.PARAMETER\t${paramKey}\n\t${paramDescription}\n\n''')
        return paramTemplate.substitute(
            paramKey=k, paramDescription=v)

    def get_header(self):
        sb = []
        sb.append('<#\n')
        sb.append(self.get_item(
            'SYNOPSIS', 'Autogenerated from ' + os.path.basename(self.origin_file)))
        sb.append(self.get_item(
            'DESCRIPTION', self.description))

        for key, value in self.parameters:
            desc = key + " [" + value["type"] + "]"
            try:
                for pkey, pvalue in value["metadata"].items():
                    if(pkey == "description"):
                        desc = pvalue
            except:
                pass
            sb.append(self.get_param_item(key, desc))

        if self.links is not None:
            sb.append(self.get_item('LINK', '\n'.join(self.links)))

        sb.append("\n#>\n")
        return ''.join(sb)
